sonar.projectKey=fastapi-kafka
sonar.projectName=FastAPI Kafka App
sonar.projectVersion=1.0

# Path to the source directories
sonar.sources=common,services,main.py,consumer.py

# Path to tests
# sonar.tests=tests

# Code coverage report path
sonar.python.coverage.reportPaths=coverage.xml

# Exclude virtual environments and migrations from analysis
sonar.exclusions=venv/**,alembic/**,**/*.pyc,**/*__pycache__*/**
