apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dipu-sharma/fast_kafka.git' # Replace with actual Git repository URL
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
